### ISSUE TITLE
Front-End Research

### ISSUE THREAD

**Issue by RomanHyde** [Frictionless-Faction/FricFracChat#2]
We are using React for the front end.

Please pool any resources, research and documentation here that you think may be useful for the front-end I can add them to the wiki for future reference.

**Assignees**
Jess, Danny and Mina

_The wiki can be found [here](https://github.com/Frictionless-Faction/FricFracChat/wiki)!_

**Comment by dannyvsm** [comment]
Some react libraries that may be useful for both the design and functionality of our app:

- [Styled Components](https://styled-components.com/)
- [React-use](https://github.com/streamich/react-use)

**Comment by RomanHyde** [comment]
> Some react libraries that may be useful for both the design and functionality of our app:
> 
> * [Styled Components](https://styled-components.com/)
> * [React-use](https://github.com/streamich/react-use)

Danny you're amazing, thank you for sharing, I'll add this to the wiki now. 😄

**Comment by RomanHyde** [comment]
Coming to the end of the deadline so I'm closing this for now.
