### ISSUE TITLE
Upgrading the styling

### ISSUE THREAD

**Issue by jesswils** [Frictionless-Faction/FricFracChat#21]
https://styled-components.com/

https://www.youtube.com/watch?v=-FZzPHSLauc&ab_channel=PedroTech

https://www.youtube.com/watch?v=G00V4tRx1ME&ab_channel=WillCodeForViews

https://medium.com/swlh/building-modals-in-react-64d92591f4b

**Comment by RomanHyde** [comment]
Hey @Jwilss3 

**Just posting the modals we would need:**
- [ ] Logout modal (asking a person to confirm if they wish to log out)
- [ ] Edit profile modal (allows a user to edit their profile without having to leave the page)
- [ ] View profile modal (allows a user to view _but not edit_ someone else's profile by clicking on their username)
- [ ] App settings

**Comment by jesswils** [comment]
Resources: 
https://www.hongkiat.com/blog/css3-glossy-effect/
https://www.w3schools.com/css/css3_animations.asp
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Animations/Using_CSS_animations
https://animate.style/ - I don't think this is compatible with react but some inspiration
https://css-tricks.com/almanac/properties/a/animation/

**Comment by Jwilss3** [comment]
https://speckyboy.com/css-border-effects/

**Comment by RomanHyde** [comment]
Hey @Jwilss3, are you going to link a pull request to this issue or are you opening a new issue for the styling?
