### ISSUE TITLE
Styling 

### ISSUE THREAD

**Issue by jesswils** [Frictionless-Faction/FricFracChat#41]
https://speckyboy.com/css-border-effects/
https://codepen.io/dasshounak/pen/QWKKYdj
https://freefrontend.com/css-forms/
https://css-tricks.com/snippets/css/a-guide-to-flexbox/
https://css-tricks.com/gradient-borders-in-css/
https://dzone.com/articles/pure-css-slide-down-animation-1
https://getcssscan.com/css-box-shadow-examples
https://www.webfx.com/web-design/hex-to-rgb/
https://moderncss.dev/css-button-styling-guide/
https://codepen.io/pulpexploder/pen/QdPZNp

**Comment by RomanHyde** [comment]
**Note:** continued from issue #21 `Upgrade the styling`
