### ISSUE TITLE
Base of the project

### ISSUE THREAD

**Issue by Minakrv** [Frictionless-Faction/FricFracChat#8]

**Comment by RomanHyde** [comment]
![image](https://i.imgur.com/QcWlsNp.png)

Image of the error.

**Comment by RomanHyde** [comment]
![image](https://i.imgur.com/OXPvGrP.png)

The new error we are working on.
**Mina:** `feature/8`
**Roman:** `bug/8` (merged)

**Comment by RomanHyde** [comment]
whoops didn't mean to close it, Mina said she's still working on this.

**Comment by RomanHyde** [comment]
Fix up feature/8 branch issues such as display and node engines
